name: tof
channels:
  - conda-forge
dependencies:
  - python=3.13
  - numpy
  - ipykernel
  - matplotlib
  - ipywidgets
  - ipympl
  - mpl-interactions
  - tifffile
  - pyqt
  - napari
  - mrcfile
  - seaborn
  - scikit-image
  - pip:
    - mpl_image_segmenter
