[project]
name = "twtof"
version = "0.2.0"
requires-python = ">= 3.8"
dependencies=[
    "numpy",
    "h5py",
    "pandas",
    "xarray",
    "pint_xarray"
]
[project.optional-dependencies]
dev=["pytest"]
[build-system]
requires = ["uv_build >= 0.9.26, <0.10.0"]
build-backend = "uv_build"